spring:
  application:
    name: consumer-service

cloud:
  aws:
    credentials:
      accessKey: fake
      secretKey: fake
    region:
      static: ap-northeast-2
    sqs:
      endpoint: "http://localhost:4566"

input_queue: ${INPUT_QUEUE}