### 직원 전체 조회
GET {{host}}/v1/employee


### 직원 생성
POST {{host}}/v1/employee
Content-Type: application/json

{
  "username": "bgs",
  "email": "ballgaveship@gmail.com",
  "firstName": "gaveship",
  "lastName": "ball",
  "displayName": "ballgaveship",
  "dept": "backend",
  "phoneNumber": "010-1234-5678"
}

### 직원 수정
PATCH {{host}}/v1/employee/1
Content-Type: application/json

{
  "firstName": "gaveship",
  "lastName": "kong",
  "displayName": "konggaveship"
}

### 직원 삭제
DELETE {{host}}/v1/employee/1